#
# TABLE STRUCTURE FOR: media
#

DROP TABLE IF EXISTS `media`;

CREATE TABLE `media` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `media_type_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `body` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `filename` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `metadata` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  `created_at` datetime DEFAULT current_timestamp(),
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `media_type_id` (`media_type_id`),
  CONSTRAINT `media_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `media_ibfk_2` FOREIGN KEY (`media_type_id`) REFERENCES `media_types` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('1', '1', '1', 'Qui qui sit repudiandae quo. Repellat qui corporis et excepturi similique itaque. Voluptate nihil omnis inventore. Beatae aut aperiam quisquam ea at ut qui.', 'et', 303968, NULL, '1981-01-04 01:38:02', '2003-05-13 02:26:01');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('2', '2', '2', 'Delectus consequatur qui dolorem sint. Enim voluptatum ducimus nulla fuga nesciunt fuga. Officiis qui maxime omnis et sit.', 'non', 23, NULL, '1975-06-28 08:05:35', '1999-07-17 22:26:18');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('3', '3', '3', 'Et assumenda quisquam similique quibusdam. Fugit quis dolorum consectetur voluptatibus voluptatem autem. Occaecati repellendus quam magnam voluptatibus.', 'qui', 2031089, NULL, '2017-04-09 07:38:21', '1990-05-17 15:38:57');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('4', '4', '4', 'Sed eveniet necessitatibus earum incidunt commodi amet eaque. Sint ipsum vitae expedita voluptatibus consequatur voluptatibus ut. Deserunt error maiores corrupti nemo et rerum provident. In minima qui dolor est officiis vitae nisi.', 'est', 737200306, NULL, '2018-05-24 06:00:05', '1981-08-20 20:54:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('5', '5', '5', 'Omnis dolor ipsum voluptas. Ipsa voluptas sint sit ut hic voluptatem vitae nostrum. Quia optio nisi rerum sint sed voluptatem. Culpa dolor perferendis asperiores velit deserunt nobis.', 'qui', 255, NULL, '2007-11-08 10:27:40', '2017-10-18 13:30:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('6', '6', '6', 'Asperiores odit doloribus non est. Provident fuga quaerat sed quas repellat. Molestiae dicta consectetur et explicabo ut et.', 'esse', 540479, NULL, '1993-08-12 02:22:21', '2009-09-22 11:41:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('7', '7', '7', 'Consequatur sapiente qui exercitationem deleniti pariatur aperiam sed. In et facere quas consequuntur. Voluptatem voluptas consequatur est sint. Sit ratione culpa harum.', 'facere', 0, NULL, '1989-09-03 20:13:26', '1979-01-24 00:23:30');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('8', '8', '8', 'Et vel atque ad dignissimos esse rerum. Sit perferendis facere sed et veniam cum. Harum suscipit ut laudantium pariatur voluptas doloribus.', 'aperiam', 0, NULL, '1973-02-26 16:48:06', '1981-05-23 17:50:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('9', '9', '9', 'Non necessitatibus veniam nobis qui beatae nam. Ullam quisquam voluptas perferendis est veritatis laboriosam. Consequatur eos beatae et.', 'molestiae', 704873, NULL, '1984-12-23 14:24:27', '1990-07-03 06:08:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('10', '10', '10', 'Voluptatem aut aliquam consequatur. Eligendi fugiat fugit omnis omnis illo quia delectus. Natus recusandae amet et placeat consequuntur officiis.', 'nam', 4126058, NULL, '2015-12-04 13:55:54', '2017-03-15 02:04:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('11', '11', '11', 'Consequuntur itaque qui tenetur nesciunt. Fugit soluta iste in est. Porro voluptas consequatur est quam. Eos aut ratione odit aut amet aut assumenda.', 'deserunt', 921, NULL, '1991-11-03 02:42:10', '2014-01-29 09:13:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('12', '12', '12', 'Quo maiores dignissimos sint explicabo praesentium provident. Voluptatem magni ratione et ea ducimus iusto velit. Et aut eligendi voluptates enim sunt exercitationem sit.', 'ab', 77628335, NULL, '1979-09-12 03:55:46', '2015-01-25 14:42:38');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('13', '13', '13', 'Et mollitia omnis ipsa sed. Neque et ipsa soluta a magni eligendi provident. Et occaecati aut omnis architecto necessitatibus quod ex sed.', 'ullam', 1, NULL, '1987-08-10 06:17:52', '1998-09-27 19:42:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('14', '14', '14', 'Laudantium accusamus quasi et voluptatibus dolore qui. Soluta exercitationem nesciunt pariatur aut distinctio. Reprehenderit nemo maiores eum dolores odio.', 'rem', 62609, NULL, '1986-03-28 04:17:30', '1977-09-29 23:01:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('15', '15', '15', 'Quis et sed a nihil non. A laborum maxime quidem nihil. Ullam minima modi ut esse. Explicabo doloremque animi labore.', 'maxime', 4, NULL, '1971-03-23 15:58:33', '2010-08-10 06:34:44');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('16', '16', '16', 'Quis culpa ut ad asperiores vel pariatur. Et dolor laudantium quis facere quaerat in molestiae quia.', 'enim', 5739863, NULL, '1990-05-24 19:48:18', '1984-04-23 23:28:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('17', '17', '17', 'Modi quia assumenda excepturi quis quasi amet sed. Qui et unde velit voluptatem sunt tempore. Voluptates vel ullam blanditiis quibusdam ullam optio et.', 'et', 51045156, NULL, '1986-05-27 21:33:48', '1975-10-25 13:38:16');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('18', '18', '18', 'Nisi velit quidem magni omnis enim commodi. Iusto facilis ad atque dolores. Nihil a veniam dolores quod mollitia accusamus.', 'nobis', 70, NULL, '1981-03-25 08:19:58', '1983-01-09 05:14:30');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('19', '19', '19', 'Expedita unde porro et. Beatae repellendus nisi cumque et necessitatibus. Iusto sed et doloremque cumque. Aperiam ab qui impedit. Nisi possimus excepturi assumenda non illum nihil.', 'dolore', 71129, NULL, '2017-10-10 16:09:07', '1993-07-23 22:04:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('20', '20', '20', 'Tenetur sit non vitae doloribus aliquid quidem. Molestiae eligendi et itaque ipsa omnis sunt. Deserunt iusto adipisci sed rem nisi. Optio accusantium temporibus voluptatum maiores qui quam. Quae eaque consequuntur voluptas laboriosam ducimus non nihil.', 'itaque', 40, NULL, '1978-11-15 03:52:09', '2018-03-18 00:41:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('21', '21', '21', 'In quas qui dolor in. Eius porro sequi quo dolorum et alias. Aut provident voluptatem accusamus.', 'aliquid', 379, NULL, '1974-08-19 17:37:15', '1996-07-26 00:36:57');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('22', '22', '22', 'Expedita ipsa sit illo vel quos sed delectus. Ducimus hic soluta doloremque sequi commodi et. Non non corrupti nam minima enim necessitatibus porro.', 'voluptas', 32, NULL, '1989-12-19 04:15:49', '2017-04-11 00:21:14');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('23', '23', '23', 'Animi temporibus expedita quidem quia et aut ab. Non repudiandae rerum in harum voluptatum. Rerum provident ut corrupti qui debitis.', 'eligendi', 7, NULL, '1973-11-16 17:11:08', '1989-02-20 16:33:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('24', '24', '24', 'Est autem quibusdam ullam nostrum consequatur saepe. Voluptatem aspernatur qui qui est. Nihil quae sed quas. Labore quo ut quos non dolor quisquam. Non dolores commodi voluptatibus dicta error.', 'ut', 85, NULL, '1972-10-25 12:46:49', '1993-03-09 08:26:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('25', '25', '25', 'Eum modi aut laboriosam velit. Consequatur id sint veritatis sint id voluptas. Nisi voluptatem optio illum cum atque nihil.', 'voluptas', 31, NULL, '1991-06-28 02:48:17', '2014-04-17 12:08:04');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('26', '26', '26', 'Odit eos sunt eum provident neque nesciunt. Ut repellat possimus inventore dicta consequatur. Autem adipisci ut facilis mollitia laudantium. Soluta molestias alias neque sint.', 'explicabo', 66265710, NULL, '2019-03-03 03:13:27', '2010-09-01 08:32:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('27', '27', '27', 'Et in recusandae incidunt consequuntur. Voluptas delectus rerum dolores ex sunt facere libero vero. Dignissimos nulla dolorum qui suscipit.', 'officia', 968174, NULL, '1982-07-31 02:09:18', '1985-06-11 12:26:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('28', '28', '28', 'At iusto qui harum. Exercitationem illo eius ipsam fugit vitae voluptates atque. Autem natus aliquam fugiat aperiam reprehenderit.', 'ullam', 701, NULL, '2012-04-21 17:58:12', '2016-12-07 01:22:01');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('29', '29', '29', 'Assumenda asperiores eum velit voluptas. Optio nulla molestiae quisquam provident nesciunt. Impedit distinctio voluptatum fugit et temporibus aut temporibus rerum.', 'quia', 722563, NULL, '2002-05-08 12:33:47', '1992-04-21 20:31:14');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('30', '30', '30', 'Omnis nihil consequuntur aut soluta. Omnis quia suscipit dignissimos vero deserunt omnis. Corporis dolorem dicta aliquam vitae eius reprehenderit.', 'dolorem', 5140, NULL, '1997-04-18 14:13:31', '1970-03-06 18:59:22');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('31', '31', '31', 'Laudantium numquam ab cumque eos fugiat velit iure. Eos dolor totam illum esse. Recusandae veniam aut modi ea quae tenetur. Vel tenetur reiciendis aliquam sit voluptas.', 'praesentium', 0, NULL, '2009-10-12 15:13:59', '2001-01-12 00:07:29');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('32', '32', '32', 'Nihil explicabo dolores est. Hic tempora vel rem provident asperiores. Voluptates sunt necessitatibus repellendus similique architecto est voluptas.', 'molestiae', 30, NULL, '2012-03-19 18:23:05', '2018-11-18 13:18:50');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('33', '33', '33', 'Vitae non eius consequuntur. Quo pariatur nihil cupiditate vero voluptatem. Consequuntur vitae aut exercitationem qui odio et. Corrupti ab doloremque nulla eum esse.', 'reiciendis', 48696, NULL, '1980-06-27 22:56:17', '1971-04-27 23:55:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('34', '34', '34', 'Maxime voluptatibus autem non occaecati molestiae ut. Eum explicabo rerum saepe adipisci sed nihil consequatur. Accusamus ab ullam aliquam quia nihil quia consequatur.', 'iure', 169007, NULL, '1992-10-15 01:30:24', '1995-07-05 03:53:54');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('35', '35', '35', 'Aut rerum rerum ut voluptatum modi dicta. Voluptatum quia in non nihil culpa cum non accusamus.', 'totam', 81190, NULL, '1976-07-19 23:10:18', '2017-07-31 22:32:49');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('36', '36', '36', 'Saepe vitae deserunt aut quibusdam quia perspiciatis. Enim aut distinctio molestiae nihil. Similique qui reprehenderit blanditiis recusandae exercitationem id consequatur. Eum aperiam cupiditate dicta quibusdam. Velit libero ut est dolor deleniti tempore ab.', 'sit', 94571, NULL, '2019-04-17 05:19:58', '2000-08-14 08:39:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('37', '37', '37', 'Delectus ratione voluptate labore cumque. Velit ut sint provident est recusandae quia. Minima consequatur dolorem molestias error.', 'minima', 3, NULL, '1999-08-10 08:30:57', '1985-05-23 16:01:27');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('38', '38', '38', 'Earum minima quibusdam hic pariatur aut magnam dolorum. Sint sit nisi est animi consequatur laborum. Sint reiciendis perspiciatis vel temporibus voluptas. Enim iusto nesciunt enim corrupti. Fuga eum alias et qui eaque nemo est.', 'voluptas', 8211, NULL, '1999-05-13 02:50:13', '1990-01-25 07:01:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('39', '39', '39', 'Quia et quos sequi et suscipit. Non magnam non enim est cum. Impedit rerum aut sed aperiam.', 'voluptate', 902159, NULL, '2008-08-27 23:16:40', '1971-10-30 02:33:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('40', '40', '40', 'Qui sed deleniti est inventore harum. Nesciunt et enim nam consequuntur. Voluptatibus consequatur eveniet temporibus blanditiis similique molestiae.', 'et', 985, NULL, '1992-06-04 09:47:21', '1980-10-13 06:08:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('41', '41', '41', 'Saepe est distinctio nihil autem amet eum quam. Quod aliquam aut sit quia et delectus tempore. Voluptas labore fugiat consectetur sit. Doloremque et cumque est fuga praesentium.', 'totam', 13, NULL, '1993-03-24 03:29:56', '1995-07-28 16:36:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('42', '42', '42', 'Praesentium sed maxime ipsam totam. Fugit possimus fugiat labore velit nulla ut.', 'explicabo', 0, NULL, '1998-08-05 19:18:59', '2011-03-28 21:36:16');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('43', '43', '43', 'Minima officia aut veniam placeat eligendi et. Non consequatur eius ullam dolorum. Et quod ut iste.', 'praesentium', 3535, NULL, '1984-06-03 19:01:33', '1979-08-09 07:34:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('44', '44', '44', 'Libero nisi assumenda iusto est. Ad rerum non dolor nihil eligendi. Et libero blanditiis nihil officia.', 'et', 50514, NULL, '1985-03-30 22:45:43', '2007-02-09 09:39:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('45', '45', '45', 'Doloribus aliquam est ut alias qui. Voluptas est delectus pariatur. Et voluptas eaque cumque sed nihil.', 'aut', 9058153, NULL, '1982-05-31 22:36:23', '1970-08-28 15:25:25');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('46', '46', '46', 'In id aliquam enim in. Dolore et blanditiis libero. Sit quisquam nesciunt consequatur eveniet dolorum. Praesentium necessitatibus asperiores non qui temporibus rem molestiae.', 'harum', 9724, NULL, '1973-08-19 09:53:27', '1986-03-20 22:21:59');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('47', '47', '47', 'Beatae distinctio sapiente saepe aut ut et. Nostrum suscipit illo porro officiis aut. Odit quae accusantium reprehenderit eos voluptatem totam rerum. Ratione qui odio est molestias.', 'temporibus', 41052, NULL, '2009-10-22 07:54:38', '1996-10-24 23:23:15');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('48', '48', '48', 'Rerum enim eveniet cupiditate voluptatum accusantium aspernatur a. Cupiditate labore nemo debitis. Aut et eum voluptas mollitia vel delectus sed id.', 'quis', 0, NULL, '1970-08-28 09:56:58', '1970-09-30 22:07:23');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('49', '49', '49', 'Voluptatum et modi repudiandae odio commodi quod suscipit. Est officiis odit rerum quis eius dolores nihil tenetur. Corporis cum assumenda culpa consequuntur. Beatae earum at vel deleniti ratione quibusdam aut.', 'veniam', 84, NULL, '2015-01-18 19:07:54', '1997-11-18 00:38:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('50', '50', '50', 'Dolorem voluptas quisquam molestiae vel impedit libero. Fugit deleniti aut consequuntur et sit unde dolores. Sint vero veritatis pariatur cumque sit qui. Iure quisquam voluptate adipisci possimus aspernatur laboriosam vel voluptatem.', 'enim', 2, NULL, '1994-08-25 14:27:09', '1974-02-08 02:56:26');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('51', '51', '51', 'Deserunt aut voluptate excepturi eveniet cumque. Est iure in dolor officia saepe quam dolore. Laborum nobis quam odio rem provident natus laboriosam qui.', 'beatae', 15959132, NULL, '1987-01-14 19:49:29', '2001-08-20 11:54:57');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('52', '52', '52', 'Consequatur nesciunt quod aut. Id laboriosam eum laudantium rerum nihil quod. Ipsum similique quia aut aut qui quam omnis. Aliquid quos quia ipsa quis nemo deleniti eligendi officia.', 'harum', 220555, NULL, '2004-01-31 17:15:14', '2009-02-07 02:04:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('53', '53', '53', 'Quia aut quibusdam error. Vero dignissimos numquam facilis veniam. Voluptates voluptatem consectetur hic officia. Alias ut possimus quo fugiat rerum magni accusantium.', 'ut', 205, NULL, '2009-06-25 08:12:00', '2018-03-12 18:58:37');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('54', '54', '54', 'Soluta unde sint tenetur rerum dolorum ut. Quas id ipsa rem expedita cupiditate architecto. Molestias pariatur eum laborum commodi.', 'libero', 151542391, NULL, '1996-10-23 20:35:25', '1995-07-17 12:21:52');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('55', '55', '55', 'Omnis nam consequatur itaque. Perferendis id totam omnis sapiente. Error possimus voluptas deleniti sit reprehenderit ea et. Iure est autem doloremque quo.', 'inventore', 3834, NULL, '2001-04-19 04:15:47', '1984-12-06 07:58:55');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('56', '56', '56', 'Voluptas esse consequatur est nemo. Incidunt dolorem distinctio voluptatem placeat exercitationem dolores nam. Ab aut quod deserunt laboriosam.', 'reiciendis', 6500, NULL, '2007-04-05 06:54:13', '1997-03-29 22:05:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('57', '57', '57', 'Quod neque temporibus et unde est excepturi odio. Delectus repudiandae blanditiis omnis impedit vero sapiente. Perspiciatis consequatur consequatur debitis nisi rerum sunt dolorem.', 'nulla', 413020110, NULL, '1997-01-16 14:42:24', '1989-05-13 04:22:58');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('58', '58', '58', 'Facere laboriosam molestiae eaque non. Impedit consequuntur architecto similique libero sequi velit ea. Eligendi non et laudantium eos et impedit.', 'qui', 811, NULL, '1978-03-31 00:24:47', '1992-02-27 16:33:53');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('59', '59', '59', 'Cupiditate maiores ratione aperiam quam. Odit quae sint et quisquam. Qui non sunt modi commodi quisquam. Iusto aspernatur quaerat debitis illo asperiores.', 'doloremque', 30, NULL, '1990-06-03 16:38:33', '1972-10-28 21:59:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('60', '60', '60', 'Minus sed voluptatem non impedit id cum. Vitae et autem labore cumque amet aliquam in. Ut quo non vitae tempora sit ut non fugit.', 'sed', 1760573, NULL, '2010-08-15 21:40:09', '1975-08-18 19:06:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('61', '61', '61', 'Quaerat aliquam reiciendis dolor eveniet tempore consequatur vitae. Omnis est non enim corrupti molestiae. Eum repellat occaecati odio sit et dolores. Amet in laborum incidunt omnis quo dolorum sunt.', 'minus', 2969, NULL, '1986-12-11 14:56:40', '1973-01-07 05:13:42');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('62', '62', '62', 'Iste soluta in doloremque voluptatum enim officia. Unde exercitationem accusantium provident saepe nesciunt. Facere tenetur occaecati et illo est eaque et. Delectus quas saepe voluptatibus modi eum ex occaecati.', 'culpa', 68065921, NULL, '1988-09-05 04:59:30', '1979-12-10 21:07:31');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('63', '63', '63', 'Libero praesentium tenetur in voluptatum et et. Quia molestiae sed ut pariatur. Cumque aut corrupti soluta quo illum aliquam. Ut odio fugiat fuga enim.', 'dolor', 0, NULL, '2000-01-09 03:12:47', '1999-10-08 06:24:37');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('64', '64', '64', 'Aut et minima aperiam est a est quia adipisci. Ratione voluptatem autem vel excepturi distinctio quas reiciendis. Debitis qui cum earum voluptatem officia ea quis.', 'molestiae', 929109, NULL, '1970-01-30 05:40:16', '1991-08-08 09:51:40');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('65', '65', '65', 'Quis deserunt rem nihil aut. Neque libero voluptatibus delectus. Amet quia nobis ut atque alias. Voluptas dolorem officiis vel ab facere et.', 'fugit', 840189916, NULL, '2002-08-21 07:57:42', '1977-05-13 09:18:10');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('66', '66', '66', 'Nihil nulla eveniet voluptates occaecati. Consequatur explicabo nobis numquam quis aliquid ut. Corrupti architecto officia non ea.', 'aperiam', 91709248, NULL, '1978-02-03 15:38:20', '1972-08-22 00:50:32');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('67', '67', '67', 'Consectetur dolorem esse dolore sed nam nesciunt alias. Nesciunt labore culpa delectus aut voluptatem dolorem.', 'aut', 563271085, NULL, '2016-04-06 01:23:52', '1991-09-17 00:22:04');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('68', '68', '68', 'Totam ut ullam voluptatem suscipit alias quam. Eos ea nisi eveniet est recusandae. Est aut voluptatem ad quo qui tempora incidunt sint. Quo et doloremque soluta. Quia quam distinctio possimus veniam et.', 'odit', 6, NULL, '2012-09-08 12:19:08', '2004-03-15 09:24:47');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('69', '69', '69', 'Et facere perferendis molestias et dignissimos. Architecto ut voluptatum ut asperiores. Harum itaque tenetur nobis sunt omnis.', 'vel', 9752890, NULL, '2012-02-18 23:50:52', '1994-06-10 23:43:41');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('70', '70', '70', 'Nostrum sunt nisi libero neque. Est hic ut debitis soluta quidem. Et veniam repellat omnis hic.', 'dolor', 424, NULL, '2012-07-05 08:53:02', '2001-04-28 20:22:15');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('71', '71', '71', 'Est officiis blanditiis aut. Sequi vel quisquam sit eaque omnis. Eos libero provident dolorem autem ipsam eos occaecati. Quidem vel rerum commodi voluptate ut.', 'totam', 853, NULL, '2001-11-20 09:28:43', '2007-04-20 12:53:29');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('72', '72', '72', 'Perferendis tenetur iste corporis eligendi. Aut vero deserunt suscipit recusandae aliquam. Consequatur ipsa possimus ad nisi vitae. Reiciendis cum autem quae molestiae commodi eum.', 'eius', 11054964, NULL, '1977-03-26 12:00:44', '1989-05-26 22:50:06');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('73', '73', '73', 'Eaque ut eveniet et corrupti non. Illum perferendis inventore esse dolor dicta eos aut. Dolore corporis consequuntur voluptatem quas enim voluptate nobis. Dolore nulla velit deleniti eveniet minima enim ut voluptatem.', 'velit', 93415, NULL, '2006-07-17 15:04:36', '2016-04-01 03:43:27');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('74', '74', '74', 'Consequatur nihil non officia occaecati enim vel nemo. Dolorem velit dolores exercitationem et. Ea placeat ut aut dolores officiis. Neque sapiente quidem sunt repellat.', 'corporis', 7290817, NULL, '1977-06-20 03:16:57', '1984-08-03 01:29:37');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('75', '75', '75', 'Molestias culpa vero temporibus corrupti ea sequi numquam. Natus expedita nihil quas blanditiis assumenda voluptate sapiente.', 'corporis', 41379, NULL, '2008-06-02 00:22:34', '1988-02-18 09:21:02');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('76', '76', '76', 'Eos sed alias tenetur officia. Modi corrupti culpa eum fugit officiis qui velit. Pariatur inventore laudantium culpa aspernatur. Perferendis eos labore velit nihil.', 'consequatur', 4405, NULL, '2008-10-22 00:49:03', '1975-04-10 06:06:22');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('77', '77', '77', 'Incidunt sequi ut sunt et molestiae. Atque eius est maiores amet repudiandae molestias quae quos. Aut dolorum ut provident temporibus. Qui corrupti facere id molestiae illum qui voluptatibus.', 'commodi', 451776, NULL, '1985-01-03 00:29:34', '1998-01-22 01:38:05');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('78', '78', '78', 'Quos totam inventore eum qui quis sed. Consequatur accusamus eaque consequatur aut et. Ut sit eum voluptatibus consequatur at voluptatem dolorem. Dolorum ullam omnis deleniti ut quis ad.', 'voluptatem', 29186254, NULL, '2005-06-29 20:27:50', '2013-09-09 21:52:35');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('79', '79', '79', 'Sunt delectus vel consequuntur corrupti recusandae. Ullam cupiditate dolores sint. Modi omnis quod et velit et. Ea eum sapiente possimus at.', 'nisi', 18398, NULL, '1984-10-18 05:36:48', '1979-12-02 23:59:39');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('80', '80', '80', 'Voluptatem molestiae accusantium ducimus placeat occaecati. Consequatur et nisi qui laboriosam quo sunt quos. Iste dolore et architecto dolorem et aliquam placeat.', 'rerum', 16, NULL, '1982-09-30 00:05:23', '2010-12-02 03:17:33');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('81', '81', '81', 'Accusantium quo et voluptatem vitae dolorem optio totam vero. Aut explicabo sunt aperiam tempore aspernatur accusamus vel. Doloremque nisi labore quod ad in delectus. Quos nostrum illo voluptatem ex dolorem.', 'magni', 90665, NULL, '2010-09-12 10:51:18', '1991-03-24 10:02:07');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('82', '82', '82', 'Quaerat qui doloremque totam et. Est rerum vitae voluptas. Impedit adipisci qui vel nihil quas esse. Cum exercitationem laudantium quisquam ut et.', 'est', 9020, NULL, '1971-09-28 16:27:54', '1988-11-10 21:26:11');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('83', '83', '83', 'Doloremque ut quibusdam nesciunt et amet officiis enim. Aliquam sint vitae ipsa. Facere deserunt placeat enim. Assumenda aliquid qui provident odio atque explicabo explicabo.', 'neque', 86, NULL, '2007-07-15 23:00:11', '2004-12-05 11:23:46');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('84', '84', '84', 'Tempore aliquid nihil sint fuga distinctio. Repellat doloribus et ex non dolorem maiores. Qui natus a et vel. Beatae amet beatae sit voluptatibus et impedit et et.', 'voluptatem', 5, NULL, '1987-05-01 00:10:55', '1994-04-04 08:58:51');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('85', '85', '85', 'Voluptas nobis neque optio exercitationem repellendus. Ex repudiandae vitae et aut mollitia natus. Impedit dolores praesentium dolores nesciunt odit voluptates consequuntur.', 'praesentium', 0, NULL, '2008-04-24 06:16:40', '2014-09-04 15:35:48');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('86', '86', '86', 'Dolor maiores voluptatibus doloremque voluptas est dolores. Repudiandae nostrum exercitationem illum dolores magni. Ex earum et exercitationem deleniti ipsa. Rerum qui ipsa repellendus tempore quia dolor sed.', 'vel', 4076, NULL, '2008-03-29 00:07:16', '1970-06-08 00:49:45');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('87', '87', '87', 'Ratione sint consequatur dolore pariatur officia rem eveniet. Ut fugiat aut fugiat dolore perferendis. Et cum nulla provident animi. Doloremque ab esse perspiciatis et in quisquam quia consequatur. Alias ex voluptas doloribus omnis id nostrum.', 'nulla', 32319, NULL, '1974-07-13 00:02:18', '1987-10-13 16:55:36');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('88', '88', '88', 'Eum nulla est aliquid. Qui nisi officiis consequatur qui qui quo illo libero. Aut incidunt quo rerum recusandae et consequuntur molestias mollitia. Unde repellat praesentium accusantium laborum odit mollitia necessitatibus.', 'minima', 5214775, NULL, '1999-09-21 20:24:29', '1981-11-05 04:57:33');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('89', '89', '89', 'Omnis dolorem quis et officia aut consequatur assumenda molestias. Amet numquam est facilis magni quo non aut. Amet corporis esse et. Repellendus aut et natus quia qui provident unde.', 'eaque', 0, NULL, '2011-07-16 14:39:46', '1991-08-06 17:34:00');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('90', '90', '90', 'Vel cupiditate dolorem voluptatum molestias asperiores aut assumenda. Laborum aut aut consequatur reiciendis possimus. Ut alias ipsum et sed hic.', 'nam', 5, NULL, '1997-03-09 11:58:34', '2007-11-30 00:55:33');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('91', '91', '91', 'Libero magnam optio quia enim officia. Ut nobis tenetur nisi et nihil iure voluptas. In voluptatem vel blanditiis consequuntur. Quia vel nisi aperiam sint temporibus.', 'maiores', 487023595, NULL, '1996-05-18 01:05:33', '1987-03-07 13:29:19');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('92', '92', '92', 'Illo id repellat vel omnis dolorem ullam. Qui rem perferendis voluptate. Est et qui sequi quae et. Reprehenderit eos eaque eveniet aliquam.', 'et', 86508, NULL, '1982-03-31 23:14:59', '1977-12-06 21:11:56');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('93', '93', '93', 'Qui beatae molestias fugiat aspernatur. Non aperiam qui dignissimos blanditiis tempora. Illum cum reprehenderit tempore est eius cumque non. Ut accusantium rem et error voluptatem aperiam expedita.', 'magnam', 74, NULL, '1976-04-10 04:50:24', '2016-05-16 18:28:16');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('94', '94', '94', 'Iusto magni qui quis accusamus. Nam sunt voluptatem occaecati dolore sunt. Quas totam dolores fuga ut voluptatum repudiandae voluptas eligendi. Est eaque enim nisi voluptatem omnis.', 'recusandae', 0, NULL, '2017-01-03 14:24:08', '2002-12-08 19:01:32');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('95', '95', '95', 'Placeat quia velit ipsam. Qui quidem quaerat facilis voluptatem esse dignissimos. Quasi id et asperiores quia.', 'consequuntur', 8, NULL, '2008-07-04 14:15:09', '1975-01-29 17:10:36');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('96', '96', '96', 'Odit tempora cumque libero placeat atque et. Sapiente aut velit repudiandae corrupti harum vel. Rerum tempore est cupiditate qui eos. Perspiciatis fugit doloremque nihil labore repudiandae magni consequuntur.', 'sequi', 34839, NULL, '1972-03-23 02:11:38', '1980-06-07 22:33:38');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('97', '97', '97', 'Est consequatur praesentium molestiae facilis molestiae et. Fugiat placeat esse molestiae qui quis sapiente. Ut iste ipsam et qui fuga eligendi.', 'et', 6, NULL, '1989-11-01 18:19:52', '1989-10-17 03:22:14');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('98', '98', '98', 'Veritatis mollitia occaecati accusamus voluptatem earum aut. Ea est et est id. Commodi eveniet non nam in.', 'officia', 3398, NULL, '1982-06-27 04:41:48', '1981-02-16 10:05:30');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('99', '99', '99', 'Quia optio omnis deserunt nam rerum. Excepturi et sit possimus totam praesentium. Minima quod ut porro omnis enim qui. Ex reiciendis ea aut ut dolor blanditiis perspiciatis.', 'placeat', 75122, NULL, '2018-10-11 21:14:50', '1991-05-06 05:21:27');
INSERT INTO `media` (`id`, `media_type_id`, `user_id`, `body`, `filename`, `size`, `metadata`, `created_at`, `updated_at`) VALUES ('100', '100', '100', 'Soluta iure quam vitae molestiae et. Ut enim ab quaerat vero. Necessitatibus natus impedit dicta consequatur.', 'est', 234263298, NULL, '2018-05-09 22:04:28', '1991-04-07 07:34:51');


