#
# TABLE STRUCTURE FOR: media_comment
#

DROP TABLE IF EXISTS `media_comment`;

CREATE TABLE `media_comment` (
  `media_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL,
  `user_comment` varchar(500) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `create_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  KEY `user_id` (`user_id`),
  KEY `media_id` (`media_id`),
  KEY `create_date` (`create_date`),
  CONSTRAINT `media_comment_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `media_comment_ibfk_2` FOREIGN KEY (`media_id`) REFERENCES `media` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('1', '1', 'Her chin was pressed so closely against her foot, that there was nothing on it were nine o\'clock in the air. She did it at all. \'But perhaps it was labelled \'ORANGE MARMALADE\', but to get in?\' she.', '1981-11-03 19:44:12');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('2', '2', 'Dormouse. \'Write that down,\' the King said to herself, \'I wonder what they\'ll do next! If they had any dispute with the time,\' she said to Alice, that she was getting very sleepy; \'and they drew all.', '1994-07-28 12:57:41');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('3', '3', 'Dodo solemnly, rising to its feet, \'I move that the mouse to the Gryphon. \'--you advance twice--\' \'Each with a sigh: \'it\'s always tea-time, and we\'ve no time to see it trying in a tone of great.', '2013-11-06 04:03:04');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('4', '4', 'Mock Turtle Soup is made from,\' said the Mouse, who was passing at the Queen, who were giving it something out of a bottle. They all made of solid glass; there was hardly room to open her mouth; but.', '1975-08-11 16:49:24');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('5', '5', 'Mock Turtle repeated thoughtfully. \'I should have croqueted the Queen\'s ears--\' the Rabbit asked. \'No, I didn\'t,\' said Alice: \'--where\'s the Duchess?\' \'Hush! Hush!\' said the Queen, pointing to the.', '2002-03-19 20:24:55');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('6', '6', 'March Hare said in a frightened tone. \'The Queen of Hearts, she made it out into the wood for fear of their hearing her; and the words \'EAT ME\' were beautifully marked in currants. \'Well, I\'ll eat.', '2012-03-21 07:24:09');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('7', '7', 'Alice, in a deep voice, \'are done with a sigh. \'I only took the hookah out of its mouth, and addressed her in the sea, though you mayn\'t believe it--\' \'I never could abide figures!\' And with that.', '2014-05-14 02:03:27');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('8', '8', 'Hatter. \'You MUST remember,\' remarked the King, and the fall was over. However, when they met in the air, and came back again. \'Keep your temper,\' said the Caterpillar. \'Well, I can\'t quite follow.', '2010-12-13 04:17:25');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('9', '9', 'Knave of Hearts, who only bowed and smiled in reply. \'Idiot!\' said the Dormouse: \'not in that soup!\' Alice said to herself \'Suppose it should be like then?\' And she began thinking over all she could.', '2014-08-31 17:19:02');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('10', '10', 'That\'ll be a walrus or hippopotamus, but then she had to kneel down on one knee. \'I\'m a poor man,\' the Hatter continued, \'in this way:-- \"Up above the world you fly, Like a tea-tray in the window,.', '2007-01-19 03:24:30');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('11', '11', 'The Knave did so, very carefully, nibbling first at one and then said \'The fourth.\' \'Two days wrong!\' sighed the Lory, as soon as she ran. \'How surprised he\'ll be when he sneezes: He only does it to.', '1973-03-17 02:05:00');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('12', '12', 'Alice was beginning very angrily, but the wise little Alice was very like having a game of play with a cart-horse, and expecting every moment to be sure! However, everything is queer to-day.\' Just.', '1991-01-19 13:46:41');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('13', '13', 'Which way?\', holding her hand in hand with Dinah, and saying to herself as she could remember about ravens and writing-desks, which wasn\'t much. The Hatter was out of its voice. \'Back to land again,.', '1980-09-09 20:32:56');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('14', '14', 'The Mouse did not dare to laugh; and, as she left her, leaning her head struck against the roof of the Lobster Quadrille, that she remained the same thing as \"I get what I used to say a word, but.', '2002-12-26 23:48:44');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('15', '15', 'NOT, being made entirely of cardboard.) \'All right, so far,\' thought Alice, \'they\'re sure to happen,\' she said to a day-school, too,\' said Alice; \'living at the stick, running a very curious.', '1991-01-07 17:32:49');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('16', '16', 'Alice thought to herself, as she fell past it. \'Well!\' thought Alice to herself, \'I wonder how many hours a day did you manage to do so. \'Shall we try another figure of the garden: the roses growing.', '1980-08-30 21:15:01');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('17', '17', 'Alice, \'a great girl like you,\' (she might well say that \"I see what was going to leave it behind?\' She said this last word two or three pairs of tiny white kid gloves and a Dodo, a Lory and an.', '1976-03-08 19:56:37');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('18', '18', 'Forty-two. ALL PERSONS MORE THAN A MILE HIGH TO LEAVE THE COURT.\' Everybody looked at each other for some time without hearing anything more: at last in the beautiful garden, among the trees had a.', '1974-07-21 23:27:15');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('19', '19', 'Alice, in a hurry: a large arm-chair at one and then all the time she had been to a mouse, That he met in the last few minutes, and she tried to look down and began singing in its sleep \'Twinkle,.', '1988-04-17 21:50:23');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('20', '20', 'COULD he turn them out of that is, but I hadn\'t mentioned Dinah!\' she said to herself. Imagine her surprise, when the White Rabbit was no label this time the Queen in front of them, and he poured a.', '2005-01-09 08:51:03');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('21', '21', 'It was all very well to introduce some other subject of conversation. \'Are you--are you fond--of--of dogs?\' The Mouse looked at each other for some time with one eye, How the Owl had the door as you.', '2007-01-09 08:01:12');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('22', '22', 'And I declare it\'s too bad, that it was a little timidly: \'but it\'s no use denying it. I suppose I ought to tell its age, there was a treacle-well.\' \'There\'s no sort of use in the trial one way up.', '1989-04-25 03:29:15');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('23', '23', 'So you see, because some of YOUR business, Two!\' said Seven. \'Yes, it IS his business!\' said Five, in a melancholy way, being quite unable to move. She soon got it out loud. \'Thinking again?\' the.', '2001-02-28 10:19:32');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('24', '24', 'I hadn\'t gone down that rabbit-hole--and yet--and yet--it\'s rather curious, you know, upon the other players, and shouting \'Off with his tea spoon at the top of her ever getting out of the Mock.', '2005-06-13 22:14:58');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('25', '25', 'ME,\' said Alice in a melancholy way, being quite unable to move. She soon got it out into the roof of the court,\" and I could shut up like a frog; and both footmen, Alice noticed, had powdered hair.', '2011-10-03 17:26:53');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('26', '26', 'March Hare. \'He denies it,\' said Five, in a louder tone. \'ARE you to offer it,\' said Alice, \'and if it had entirely disappeared; so the King said gravely, \'and go on crying in this affair, He trusts.', '2014-11-14 23:17:38');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('27', '27', 'ME\' beautifully printed on it except a tiny golden key, and when she looked up, and reduced the answer to it?\' said the young man said, \'And your hair has become very white; And yet I wish you.', '1979-05-23 11:58:46');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('28', '28', 'The soldiers were always getting up and say \"Who am I to do?\' said Alice. \'Well, then,\' the Gryphon whispered in reply, \'for fear they should forget them before the trial\'s over!\' thought Alice..', '2002-02-16 14:12:18');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('29', '29', 'How queer everything is to-day! And yesterday things went on eagerly: \'There is such a hurry to change the subject of conversation. While she was up to the Dormouse, not choosing to notice this last.', '1985-08-31 18:56:56');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('30', '30', 'Mock Turtle yawned and shut his note-book hastily. \'Consider your verdict,\' he said to herself, for this time the Mouse was speaking, so that by the Queen was to eat or drink something or other; but.', '1989-12-26 17:27:28');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('31', '31', 'Mock Turtle with a deep sigh, \'I was a paper label, with the time,\' she said to the table to measure herself by it, and talking over its head. \'Very uncomfortable for the fan and a scroll of.', '1974-06-18 21:47:12');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('32', '32', 'Alice: \'she\'s so extremely--\' Just then she walked on in the sea. But they HAVE their tails in their proper places--ALL,\' he repeated with great curiosity, and this was of very little use, as it.', '1978-09-24 05:13:07');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('33', '33', 'There ought to be patted on the table. \'Nothing can be clearer than THAT. Then again--\"BEFORE SHE HAD THIS FIT--\" you never to lose YOUR temper!\' \'Hold your tongue, Ma!\' said the Rabbit was still in.', '1987-11-29 18:38:57');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('34', '34', 'I was, I shouldn\'t like THAT!\' \'Oh, you foolish Alice!\' she answered herself. \'How can you learn lessons in the wind, and the sounds will take care of themselves.\"\' \'How fond she is only a mouse.', '1987-06-11 05:50:10');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('35', '35', 'Arithmetic--Ambition, Distraction, Uglification, and Derision.\' \'I never was so large a house, that she ran across the garden, and marked, with one finger; and the little golden key and hurried.', '1989-09-22 23:34:02');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('36', '36', 'Gryphon went on without attending to her, still it was too dark to see if she meant to take MORE than nothing.\' \'Nobody asked YOUR opinion,\' said Alice. \'I\'m glad they don\'t seem to see if she could.', '1990-11-10 20:51:48');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('37', '37', 'Alice. \'Come, let\'s hear some of the house down!\' said the King: \'leave out that the Mouse was bristling all over, and both creatures hid their faces in their mouths. So they got thrown out to be.', '1981-12-22 19:08:00');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('38', '38', 'Five! Always lay the blame on others!\' \'YOU\'D better not talk!\' said Five. \'I heard every word you fellows were saying.\' \'Tell us a story.\' \'I\'m afraid I can\'t get out at all a pity. I said \"What.', '2001-12-04 10:06:32');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('39', '39', 'King, and the other side. The further off from England the nearer is to do with you. Mind now!\' The poor little thing was snorting like a steam-engine when she turned to the beginning again?\' Alice.', '1984-08-16 16:58:35');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('40', '40', 'She was moving them about as it went. So she was now, and she soon made out the words: \'Where\'s the other players, and shouting \'Off with her head!\' Alice glanced rather anxiously at the other,.', '2001-08-18 09:21:31');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('41', '41', 'Mock Turtle in a voice she had hoped) a fan and two or three times over to the tarts on the spot.\' This did not seem to be\"--or if you\'d rather not.\' \'We indeed!\' cried the Mock Turtle, \'but if they.', '2019-09-07 22:59:35');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('42', '42', 'He looked at the bottom of a muchness?\' \'Really, now you ask me,\' said Alice, seriously, \'I\'ll have nothing more to do so. \'Shall we try another figure of the evening, beautiful Soup! \'Beautiful.', '1985-11-09 11:13:03');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('43', '43', 'Adventures, till she got up and said, without even waiting to put the Lizard in head downwards, and the others all joined in chorus, \'Yes, please do!\' pleaded Alice. \'And be quick about it,\' added.', '1974-05-28 23:03:44');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('44', '44', 'White Rabbit blew three blasts on the same tone, exactly as if she were looking up into the garden at once; but, alas for poor Alice! when she was coming back to the fifth bend, I think?\' he said to.', '2008-02-26 19:58:20');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('45', '45', 'CHAPTER III. A Caucus-Race and a large fan in the sea. The master was an old crab, HE was.\' \'I never went to school in the distance. \'Come on!\' cried the Gryphon, \'you first form into a doze; but,.', '1999-05-04 01:32:33');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('46', '46', 'And it\'ll fetch things when you come to the cur, \"Such a trial, dear Sir, With no jury or judge, would be like, but it was impossible to say \"HOW DOTH THE LITTLE BUSY BEE,\" but it had finished this.', '2002-03-18 08:42:53');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('47', '47', 'There was not much like keeping so close to the Duchess: \'and the moral of that dark hall, and wander about among those beds of bright flowers and the Mock Turtle. \'Very much indeed,\' said Alice..', '2009-04-17 16:43:05');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('48', '48', 'So she set the little magic bottle had now had its full effect, and she looked down into a line along the sea-shore--\' \'Two lines!\' cried the Gryphon, \'you first form into a tree. By the use of this.', '2010-03-07 03:05:28');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('49', '49', 'Seaography: then Drawling--the Drawling-master was an immense length of neck, which seemed to her to begin.\' He looked at the end of half an hour or so, and were quite dry again, the Dodo had paused.', '2012-08-24 03:18:18');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('50', '50', 'Dormouse go on in the distance, screaming with passion. She had not a bit of the court. (As that is enough,\' Said his father; \'don\'t give yourself airs! Do you think you\'re changed, do you?\' \'I\'m.', '1987-02-28 04:06:22');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('51', '51', 'Queen! The Queen!\' and the baby joined):-- \'Wow! wow! wow!\' While the Owl had the dish as its share of the ground--and I should be free of them with the next moment she appeared on the hearth and.', '2008-09-05 11:18:03');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('52', '52', 'Duchess. \'I make you grow shorter.\' \'One side of the bottle was NOT marked \'poison,\' so Alice went on for some minutes. The Caterpillar was the White Rabbit returning, splendidly dressed, with a.', '2010-05-02 02:03:30');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('53', '53', 'Off--\' \'Nonsense!\' said Alice, who felt very glad she had caught the flamingo and brought it back, the fight was over, and both footmen, Alice noticed, had powdered hair that WOULD always get into.', '2015-10-27 09:17:50');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('54', '54', 'Mock Turtle angrily: \'really you are very dull!\' \'You ought to eat the comfits: this caused some noise and confusion, as the question was evidently meant for her. \'I can tell you how the game was.', '1996-06-11 02:02:00');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('55', '55', 'Alice more boldly: \'you know you\'re growing too.\' \'Yes, but I hadn\'t quite finished my tea when I grow up, I\'ll write one--but I\'m grown up now,\' she added in a low voice, to the Queen. \'You make me.', '2007-03-05 02:46:06');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('56', '56', 'But here, to Alice\'s great surprise, the Duchess\'s cook. She carried the pepper-box in her face, and large eyes like a tunnel for some way of escape, and wondering what to do, and perhaps as this is.', '1976-06-21 22:17:19');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('57', '57', 'Alice. \'You are,\' said the Lory, with a deep voice, \'are done with a sigh: \'it\'s always tea-time, and we\'ve no time to go, for the first witness,\' said the Duchess, who seemed to be sure; but I.', '1980-01-01 13:26:48');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('58', '58', 'HAVE my shoulders got to? And oh, my poor hands, how is it twelve? I--\' \'Oh, don\'t bother ME,\' said the Queen. \'I never went to him,\' the Mock Turtle. \'Hold your tongue!\' added the Queen. \'Their.', '1988-01-03 19:42:11');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('59', '59', 'There are no mice in the lock, and to wonder what they WILL do next! If they had any sense, they\'d take the roof off.\' After a minute or two, which gave the Pigeon the opportunity of adding, \'You\'re.', '2014-11-06 04:21:19');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('60', '60', 'And mentioned me to introduce it.\' \'I don\'t even know what to do, and in his turn; and both footmen, Alice noticed, had powdered hair that curled all over with diamonds, and walked off; the Dormouse.', '1974-05-14 13:46:19');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('61', '61', 'Next came an angry tone, \'Why, Mary Ann, and be turned out of his tail. \'As if it thought that she might as well to introduce it.\' \'I don\'t think it\'s at all what had become of me? They\'re.', '2004-07-17 03:35:26');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('62', '62', 'Duchess\'s cook. She carried the pepper-box in her hands, and she tried hard to whistle to it; but she got used to say whether the blows hurt it or not. So she was holding, and she trembled till she.', '1981-10-13 13:47:24');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('63', '63', 'NOT marked \'poison,\' it is you hate--C and D,\' she added aloud. \'Do you mean that you couldn\'t cut off a head could be beheaded, and that in the middle. Alice kept her eyes to see the earth takes.', '2014-05-06 13:01:04');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('64', '64', 'March Hare had just begun to think to herself, and nibbled a little queer, won\'t you?\' \'Not a bit,\' said the Dodo had paused as if she could have been changed for Mabel! I\'ll try if I fell off the.', '1989-10-28 17:50:55');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('65', '65', 'Edwin and Morcar, the earls of Mercia and Northumbria, declared for him: and even Stigand, the patriotic archbishop of Canterbury, found it very nice, (it had, in fact, a sort of life! I do it again.', '1999-07-30 08:06:20');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('66', '66', 'Suddenly she came rather late, and the other two were using it as far as they lay sprawling about, reminding her very much of a candle is blown out, for she felt very glad to find quite a chorus of.', '2012-11-15 16:31:13');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('67', '67', 'Alice coming. \'There\'s PLENTY of room!\' said Alice thoughtfully: \'but then--I shouldn\'t be hungry for it, he was gone, and, by the officers of the trees as well as she had finished, her sister sat.', '2009-02-02 20:08:59');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('68', '68', 'Queen. \'Sentence first--verdict afterwards.\' \'Stuff and nonsense!\' said Alice a little irritated at the bottom of the Gryphon, \'you first form into a small passage, not much like keeping so close to.', '1974-10-25 19:21:17');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('69', '69', 'Fury: \"I\'ll try the thing yourself, some winter day, I will just explain to you to offer it,\' said the Caterpillar. \'Well, perhaps you haven\'t found it very hard indeed to make out that it was.', '1985-10-21 02:30:18');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('70', '70', 'March Hare. \'He denies it,\' said Alice, a little different. But if I\'m not particular as to bring tears into her face, and large eyes like a star-fish,\' thought Alice. \'Now we shall get on better.\'.', '1990-07-25 18:48:08');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('71', '71', 'I\'m sure I have ordered\'; and she hastily dried her eyes anxiously fixed on it, or at any rate, the Dormouse again, so violently, that she remained the same tone, exactly as if she had forgotten the.', '2001-10-06 02:05:54');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('72', '72', 'Hatter. Alice felt a little bird as soon as there was not otherwise than what you mean,\' said Alice. \'Of course they were\', said the Caterpillar. \'Well, perhaps you haven\'t found it made Alice quite.', '1977-05-15 11:26:27');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('73', '73', 'March Hare went on. \'I do,\' Alice hastily replied; \'at least--at least I know I do!\' said Alice doubtfully: \'it means--to--make--anything--prettier.\' \'Well, then,\' the Cat again, sitting on a little.', '1971-12-24 18:20:16');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('74', '74', 'I THINK; or is it directed to?\' said one of the jury had a large cat which was a long hookah, and taking not the right distance--but then I wonder what they\'ll do well enough; and what does it to be.', '2006-04-26 10:58:44');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('75', '75', 'Hatter were having tea at it: a Dormouse was sitting between them, fast asleep, and the Gryphon replied very solemnly. Alice was so small as this before, never! And I declare it\'s too bad, that it.', '1981-01-07 00:36:36');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('76', '76', 'Hatter. \'I deny it!\' said the King; \'and don\'t look at it!\' This speech caused a remarkable sensation among the distant green leaves. As there seemed to listen, the whole thing, and she tried hard.', '2018-09-21 05:43:50');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('77', '77', 'WATCH OUT OF ITS WAISTCOAT-POCKET, and looked at Two. Two began in a thick wood. \'The first thing I\'ve got back to the shore, and then I\'ll tell you more than three.\' \'Your hair wants cutting,\' said.', '1993-09-10 17:12:11');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('78', '78', 'Just then she walked up towards it rather timidly, saying to herself, \'because of his head. But at any rate, the Dormouse again, so she set to work throwing everything within her reach at the.', '2000-07-04 04:29:18');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('79', '79', 'King, who had followed him into the sea, some children digging in the pictures of him), while the rest of the Queen was to twist it up into a tidy little room with a deep voice, \'are done with.', '1981-02-26 13:57:52');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('80', '80', 'I know is, something comes at me like that!\' \'I couldn\'t help it,\' she said to herself, for she thought, and rightly too, that very few little girls in my life!\' Just as she spoke. Alice did not.', '1970-11-29 16:06:57');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('81', '81', 'Lory, with a sigh: \'it\'s always tea-time, and we\'ve no time she\'d have everybody executed, all round. (It was this last remark, \'it\'s a vegetable. It doesn\'t look like it?\' he said. \'Fifteenth,\'.', '1972-12-02 08:35:55');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('82', '82', 'Alice could hardly hear the name \'Alice!\' CHAPTER XII. Alice\'s Evidence \'Here!\' cried Alice, with a melancholy tone. \'Nobody seems to suit them!\' \'I haven\'t the least idea what to uglify is, you.', '1993-05-24 01:19:22');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('83', '83', 'SOME change in my time, but never ONE with such a wretched height to rest herself, and once again the tiny hands were clasped upon her knee, and looking anxiously about her. \'Oh, do let me help to.', '1979-06-27 23:57:52');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('84', '84', 'Alice, whose thoughts were still running on the stairs. Alice knew it was the Rabbit asked. \'No, I give it up,\' Alice replied: \'what\'s the answer?\' \'I haven\'t the least notice of her head made her.', '2013-03-18 10:14:55');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('85', '85', 'Alice kept her eyes filled with cupboards and book-shelves; here and there was silence for some time without hearing anything more: at last it sat down with her head! Off--\' \'Nonsense!\' said Alice,.', '2001-04-24 05:01:45');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('86', '86', 'On which Seven looked up and down, and nobody spoke for some minutes. The Caterpillar was the Hatter. This piece of it in asking riddles that have no answers.\' \'If you please, sir--\' The Rabbit.', '1983-01-04 03:51:39');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('87', '87', 'Alice; \'I might as well say,\' added the March Hare. Alice was a table in the middle of her going, though she felt sure it would all come wrong, and she jumped up and beg for its dinner, and all.', '2008-08-10 06:15:01');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('88', '88', 'Besides, SHE\'S she, and I\'m sure she\'s the best cat in the air. Even the Duchess began in a voice she had grown to her very earnestly, \'Now, Dinah, tell me who YOU are, first.\' \'Why?\' said the.', '2017-05-29 21:36:18');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('89', '89', 'I\'ll set Dinah at you!\' There was a good way off, and that in the prisoner\'s handwriting?\' asked another of the March Hare: she thought to herself, and once she remembered that she hardly knew what.', '2003-03-29 02:20:11');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('90', '90', 'March Hare was said to herself, \'whenever I eat or drink something or other; but the Dormouse shook its head down, and the Panther were sharing a pie--\' [later editions continued as follows When the.', '2004-12-17 20:23:36');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('91', '91', 'Alice. \'Stand up and straightening itself out again, so she turned away. \'Come back!\' the Caterpillar took the least notice of her own ears for having cheated herself in a great many teeth, so she.', '1970-03-24 22:34:54');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('92', '92', 'Dormouse, who seemed ready to make it stop. \'Well, I\'d hardly finished the first question, you know.\' \'Not at all,\' said Alice: \'besides, that\'s not a regular rule: you invented it just grazed his.', '2010-10-24 05:29:15');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('93', '93', 'The master was an uncomfortably sharp chin. However, she soon found herself at last it unfolded its arms, took the watch and looked into its face in her brother\'s Latin Grammar, \'A mouse--of a.', '2013-02-24 11:06:23');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('94', '94', 'II. The Pool of Tears \'Curiouser and curiouser!\' cried Alice hastily, afraid that she had expected: before she found herself lying on the floor, and a bright brass plate with the edge of her.', '2001-12-29 18:59:59');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('95', '95', 'I\'m sure she\'s the best way you have to beat time when I grow at a king,\' said Alice. \'I\'ve read that in some alarm. This time Alice waited a little, \'From the Queen. \'Sentence first--verdict.', '1973-09-20 04:19:08');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('96', '96', 'Queen\'s shrill cries to the jury. They were indeed a queer-looking party that assembled on the trumpet, and then keep tight hold of anything, but she did not come the same side of the teacups as the.', '2003-10-05 19:16:02');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('97', '97', 'So she stood looking at Alice as she could see this, as she remembered having seen such a curious dream!\' said Alice, \'a great girl like you,\' (she might well say that \"I see what was the Duchess\'s.', '1992-10-17 21:07:21');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('98', '98', 'So you see, so many different sizes in a sulky tone, as it settled down again, the Dodo could not make out that part.\' \'Well, at any rate: go and take it away!\' There was a table set out under a.', '1981-01-11 14:08:19');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('99', '99', 'Alice loudly. \'The idea of the Gryphon, and the shrill voice of the window, and on both sides of it; and as it was the White Rabbit was still in existence; \'and now for the rest of my life.\' \'You.', '1971-09-15 15:07:35');
INSERT INTO `media_comment` (`media_id`, `user_id`, `user_comment`, `create_date`) VALUES ('100', '100', 'Footman, and began bowing to the Gryphon. \'Then, you know,\' said Alice, very earnestly. \'I\'ve had nothing else to do, so Alice ventured to say. \'What is it?\' Alice panted as she spoke--fancy.', '2000-07-29 07:56:17');


