#
# TABLE STRUCTURE FOR: store
#

DROP TABLE IF EXISTS `store`;

CREATE TABLE `store` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL,
  `prod_name` varchar(500) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
  `description` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `photo_albums_id` bigint(20) unsigned NOT NULL,
  `create_date` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `id` (`id`),
  KEY `photo_albums_id` (`photo_albums_id`),
  KEY `create_date` (`create_date`),
  KEY `prod_name` (`prod_name`),
  KEY `id_2` (`id`),
  CONSTRAINT `store_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `store_ibfk_2` FOREIGN KEY (`photo_albums_id`) REFERENCES `photo_albums` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('1', '1', 'qui', 'Aspernatur illum asperiores fugiat cumque deserunt. Illo eum nihil qui vitae et eaque. Ea ad quisquam porro maxime. Sed aliquam omnis aut iure ut. Qui deserunt fuga qui dolor minima dolorem.', '1', '2020-02-08 21:11:45');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('2', '2', 'illo', 'Veniam quod earum et nobis. Non at quis voluptates distinctio sit sed excepturi. Et et velit sit aperiam et qui numquam. Voluptates magnam autem qui voluptatem.', '2', '2020-01-19 18:56:56');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('3', '3', 'quis', 'Ipsam accusamus explicabo numquam unde perferendis alias saepe. Molestias qui ab provident sint voluptatum cum sapiente. Veniam et accusamus et occaecati explicabo omnis porro. Dolores qui repudiandae blanditiis atque et.', '3', '1996-04-14 17:23:47');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('4', '4', 'est', 'Quidem repellendus sunt iste similique. Rem dolores eligendi tempora.', '4', '1972-08-16 16:19:59');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('5', '5', 'voluptates', 'Ducimus est corrupti est neque quo rerum. Quam fugit ea vitae ut laborum unde. Accusamus nihil enim similique.', '5', '1999-02-07 23:11:35');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('6', '6', 'placeat', 'Aut necessitatibus impedit doloribus. Ut et voluptate ut consequuntur. Necessitatibus nihil reiciendis sint sint.', '6', '2017-09-17 07:00:51');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('7', '7', 'quos', 'Ullam quia hic laudantium voluptas commodi. Repellat magni non quae officia cupiditate nostrum provident et. Sequi corrupti non impedit aut.', '7', '2007-01-20 05:42:36');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('8', '8', 'velit', 'Id ut tempore sit. Odio eaque molestias quis deserunt. Fuga ut magni ab expedita debitis nihil.', '8', '1985-01-22 08:51:34');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('9', '9', 'dolorem', 'Autem sint sed soluta at. Quam inventore est ducimus nulla facere. Iusto aut non blanditiis nostrum. Voluptatem animi quam soluta error repudiandae debitis officia.', '9', '1980-08-02 20:40:49');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('10', '10', 'et', 'Vel temporibus repellat ab ipsa quibusdam omnis. Incidunt aliquam neque maxime qui quae non aut. Maxime est qui magni voluptatem labore.', '10', '1989-11-05 22:35:38');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('11', '11', 'nobis', 'Rem ut facilis enim quia. Eaque quisquam voluptates rem voluptatem occaecati ea voluptas. Enim eos explicabo consequatur deleniti dolores nostrum delectus. Voluptate delectus non laborum facere quia quis.', '11', '2007-07-31 06:44:15');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('12', '12', 'voluptas', 'Tempore aut libero qui ipsum. Sit laborum qui ipsam tempora qui consequatur corrupti laudantium. Temporibus voluptate deserunt sunt aperiam autem reprehenderit. Esse cumque iure vitae aut qui modi voluptatum eaque.', '12', '2009-08-14 20:13:11');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('13', '13', 'mollitia', 'Soluta nemo odit id sapiente nobis quis enim. Qui pariatur recusandae inventore neque fugiat facilis magni. Temporibus dignissimos quia consequuntur voluptas quidem magni.', '13', '1975-07-17 02:18:02');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('14', '14', 'rerum', 'Adipisci eligendi et quia debitis est sit voluptatem similique. Non magni tempora amet quidem perspiciatis aut. Qui deleniti facilis est omnis saepe.', '14', '2002-05-10 15:49:47');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('15', '15', 'sint', 'Saepe aliquid porro veritatis nam. Voluptatem quia perspiciatis sed sit minima. Voluptates ipsa vel quasi blanditiis qui qui.', '15', '1995-06-17 07:09:45');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('16', '16', 'unde', 'Veniam aliquam aut nam voluptatem. Nesciunt aut quis fugiat sit. Et possimus repellat quibusdam aut maiores. Enim impedit odit qui autem nam.', '16', '2014-08-11 22:37:11');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('17', '17', 'voluptatibus', 'Eum eum ratione consequatur. Neque necessitatibus illum quae.', '17', '1993-06-22 18:34:55');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('18', '18', 'neque', 'Architecto molestias pariatur a est rerum provident. Ut distinctio aut provident voluptatem id distinctio. Ut omnis inventore accusamus. Mollitia adipisci neque et.', '18', '1977-02-21 18:54:56');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('19', '19', 'corrupti', 'Suscipit doloremque aliquam quia eaque est. Quod quia excepturi assumenda porro. Nobis dolorem adipisci omnis architecto nemo iusto quisquam. Distinctio ad et eius velit.', '19', '1977-08-11 10:44:54');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('20', '20', 'neque', 'Illum tempore aliquid earum dignissimos maxime dignissimos. Eius eum natus debitis dolorem eum dolore. Maxime tempore excepturi ut voluptas et. Quos et dignissimos aspernatur rerum quidem doloremque eaque veritatis.', '20', '2006-11-18 09:41:28');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('21', '21', 'atque', 'Ad ipsum reiciendis placeat rerum. Optio enim numquam reprehenderit eos dolor beatae voluptas. Doloremque facilis et libero. Ea odio ut consequatur.', '21', '2009-02-02 09:01:21');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('22', '22', 'nostrum', 'Voluptate harum totam eligendi placeat et non consequatur. Et ipsam numquam fugit vitae commodi. Tenetur qui rem iste sunt nemo dolor magnam. Voluptatibus expedita et optio explicabo nesciunt voluptas omnis.', '22', '1990-06-07 19:34:43');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('23', '23', 'dicta', 'Mollitia fugiat magni reprehenderit magni quia fugit soluta sint. Aut cupiditate maxime voluptas aut asperiores quo. Quis quis rerum sequi dolores quo molestias. Distinctio hic enim earum quia nobis et aut qui.', '23', '2004-10-21 22:34:29');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('24', '24', 'quaerat', 'Ex ad nihil animi. Sit qui natus sed ad asperiores.', '24', '1981-04-06 21:49:02');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('25', '25', 'odio', 'Sequi impedit odio totam blanditiis sed omnis. Aut consequuntur iure consequatur veritatis. Commodi soluta asperiores aut veniam delectus. Sunt et est quia quo qui quis.', '25', '1990-08-19 08:21:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('26', '26', 'et', 'Mollitia illo reprehenderit laboriosam libero quibusdam voluptate recusandae facilis. Explicabo totam rerum ea porro doloremque. Et neque sequi consequatur ut explicabo velit soluta. Placeat consequatur non non est asperiores. Maiores a laboriosam quia.', '26', '2015-07-26 16:15:06');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('27', '27', 'ea', 'Deserunt tenetur sit quasi explicabo aut vel et. Et fugiat ut enim fugiat voluptas accusamus impedit. Iste quae minus in reiciendis facilis voluptatem sit. Error eaque optio ut aut.', '27', '2010-05-24 16:20:27');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('28', '28', 'error', 'Hic quia corporis quo cupiditate ex in rerum et. Ut repellendus eius cum voluptatibus nemo molestiae. Laboriosam ea itaque corrupti et.', '28', '1977-12-11 21:12:55');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('29', '29', 'ab', 'Atque eius deserunt nobis autem autem atque alias. Aut repellendus voluptas officiis corporis sint ut. Sunt quis consequatur vitae et. In aperiam expedita occaecati nesciunt.', '29', '2014-11-04 09:48:23');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('30', '30', 'placeat', 'Aut inventore accusamus quod itaque est sunt ipsa earum. Deleniti ducimus repellendus ea vel nostrum modi consequatur id. Soluta qui possimus atque dolor est vel vitae. Odio officiis est quia reprehenderit et ipsum.', '30', '1995-01-14 12:07:28');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('31', '31', 'dolor', 'Similique praesentium quia omnis aut nulla ad. Debitis quis veritatis sapiente accusantium magnam corrupti et. Quo ut tenetur harum aut in maiores eveniet quas. Id rerum rem amet nesciunt alias.', '31', '2005-11-10 16:33:44');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('32', '32', 'praesentium', 'At voluptatem quis nobis accusantium et laboriosam velit. Cum qui ut ea.', '32', '2015-10-28 07:52:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('33', '33', 'consequatur', 'Ut vel quis natus et dolorem quia. Est sapiente recusandae numquam sit magnam. Id harum enim aliquam assumenda quia culpa.', '33', '1972-10-12 10:42:36');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('34', '34', 'eveniet', 'Omnis minima deserunt quae similique nostrum architecto natus. Et expedita iusto reprehenderit eos qui omnis. Ratione reiciendis dignissimos officia tempora similique. At sunt esse aut excepturi.', '34', '2016-11-15 15:14:23');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('35', '35', 'sequi', 'Laudantium rem perspiciatis saepe laborum quae. Dolorem consequuntur est assumenda numquam voluptatum. Occaecati voluptatem deleniti odit itaque deserunt.', '35', '1986-12-09 03:16:05');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('36', '36', 'eum', 'Ut sapiente mollitia unde rerum saepe. Asperiores est vero expedita aut fugit inventore veritatis.', '36', '1984-09-02 10:41:29');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('37', '37', 'iure', 'Aut illum vel esse corporis repellat voluptatibus. Et corrupti perspiciatis totam atque qui voluptatum soluta. Sit distinctio deserunt consequatur consequuntur mollitia nisi nobis.', '37', '1996-07-17 11:17:58');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('38', '38', 'voluptatum', 'Aut sit omnis quis accusantium quia magni necessitatibus. Aut consequatur omnis ipsam a. Illum id ea quis vel asperiores ut. Rem recusandae provident consequatur ipsam ut magnam exercitationem praesentium.', '38', '1970-04-15 07:31:53');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('39', '39', 'veritatis', 'Est sapiente est doloremque reprehenderit suscipit id officia quae. Autem est iusto ea minima quas. Iusto adipisci voluptates facere vel. Sunt doloremque quia non voluptas et.', '39', '1991-12-02 03:41:04');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('40', '40', 'nulla', 'Porro voluptatibus ea est qui ut ipsum. Est laudantium molestiae veritatis saepe at. Recusandae magnam natus adipisci autem quo voluptatem. Voluptatibus eos debitis porro. Et est aspernatur corporis rerum est.', '40', '2001-01-07 21:15:58');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('41', '41', 'aliquid', 'Esse veniam modi omnis nisi ut excepturi. Quia adipisci in aut. Omnis accusamus eos est nulla qui modi. Totam eos autem sunt. Ullam aut et sit porro et iusto accusantium id.', '41', '2000-11-10 20:54:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('42', '42', 'sint', 'Deserunt earum qui et. Molestiae accusamus sunt est eligendi officia qui. Et repellendus enim laborum dicta cumque suscipit ullam quo. Illo provident ea maxime illum quaerat fugiat similique. Aliquam aut ea est beatae qui in natus.', '42', '2017-03-02 18:35:48');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('43', '43', 'enim', 'Amet dolores perferendis praesentium. Ab sit et natus consequatur est ut quam. Nemo debitis ad vitae molestiae delectus quos. Et qui rerum ex est rerum.', '43', '2009-05-03 14:16:15');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('44', '44', 'quos', 'Sit voluptatem sunt autem sed iure quia accusamus. Necessitatibus iusto suscipit suscipit. Quod et ipsum est at commodi et soluta.', '44', '1977-03-09 13:58:18');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('45', '45', 'consequatur', 'Adipisci error qui amet qui ratione quaerat quod perspiciatis. Qui aliquid in ab aliquam eaque. Qui quia fuga sed possimus voluptas aut nihil. Porro sequi ut voluptatem ut magni ut nihil.', '45', '1987-12-27 01:04:34');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('46', '46', 'placeat', 'Eius nisi facere et qui. Vel nihil veniam error accusantium a. Ut eos quisquam omnis et sunt suscipit.', '46', '2007-11-22 11:22:36');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('47', '47', 'iure', 'Doloremque rerum accusantium deleniti esse voluptas animi sit est. Rem quia quia qui similique. Saepe ipsa alias sunt quisquam qui deserunt. Ut eveniet recusandae quia delectus quo et blanditiis. Et fugit cumque quisquam aut quo et nemo.', '47', '1985-02-08 06:21:35');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('48', '48', 'non', 'Accusantium voluptatem nobis animi. Ea ea accusamus eos eius consectetur sequi qui dignissimos. Dolor voluptas asperiores ipsa neque corporis. Sapiente recusandae qui voluptatem et eum.', '48', '1980-05-20 10:06:49');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('49', '49', 'provident', 'Eum magni quisquam et quo doloremque delectus. Quibusdam saepe eligendi ad optio. Molestias voluptatem mollitia consequatur aut officiis sed voluptatibus.', '49', '1992-04-19 01:28:31');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('50', '50', 'dolorem', 'Qui dolorem voluptates odio ut architecto nihil eum. Laborum quaerat veritatis tenetur sit totam. Maxime et voluptatibus totam numquam architecto est iste.', '50', '2009-07-12 21:11:15');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('51', '51', 'et', 'Inventore quo commodi autem et et esse. Autem hic sit quibusdam quia autem ad consectetur. Et omnis amet cupiditate. Id debitis quo doloribus hic facere ut porro.', '51', '1985-07-03 06:05:30');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('52', '52', 'veritatis', 'Cupiditate reprehenderit asperiores reiciendis consequatur sint quos. Perspiciatis velit nulla eligendi id sunt reiciendis. Nostrum vero quia quod temporibus id. Dolorem id voluptate nisi ut itaque.', '52', '2012-08-24 18:45:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('53', '53', 'velit', 'Sunt alias praesentium a quasi ea doloribus. Voluptatem dolorum iure veniam et beatae. Unde sit est occaecati officiis porro modi tempora. Optio voluptatum voluptas ex sequi quidem quae ducimus.', '53', '1973-05-08 05:50:03');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('54', '54', 'incidunt', 'Autem explicabo doloremque et aut nulla. Quidem dolores quis saepe et. Et error omnis quibusdam ab consequuntur deserunt maxime. Animi ut at quas repellendus non quo.', '54', '2014-12-04 14:11:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('55', '55', 'doloribus', 'Ipsam adipisci sapiente et rerum. Exercitationem suscipit excepturi cupiditate velit nulla eveniet atque. Officia voluptatum dolor delectus nesciunt. Doloremque aut ad alias fuga quam neque et. Magni quaerat dolorem est unde aut.', '55', '1972-08-13 12:30:16');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('56', '56', 'saepe', 'Incidunt id sit inventore cum quis. Exercitationem eum quasi ab delectus. Deleniti veritatis odit dignissimos et quis maiores. Porro voluptas aut asperiores odio.', '56', '1991-01-17 06:58:49');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('57', '57', 'nesciunt', 'Modi consequatur quisquam non consequatur veniam. Distinctio consequatur animi ut in quae. Eaque ullam natus qui aliquam provident hic.', '57', '1971-07-31 17:15:51');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('58', '58', 'eligendi', 'Illum in eum aliquam et voluptas saepe excepturi. In dolor molestias atque est illo. Aut dolor quia eum excepturi. Autem quaerat fugiat quo ea veniam id sed perspiciatis.', '58', '1976-01-11 00:20:37');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('59', '59', 'et', 'Voluptas alias aut in voluptate. Laudantium aut aut omnis asperiores aut voluptatum voluptas.', '59', '1986-01-14 19:43:13');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('60', '60', 'optio', 'Blanditiis minima nostrum voluptatem dolor delectus. Et est vero quisquam sed voluptatem. Dolorum autem sed itaque delectus enim necessitatibus.', '60', '2014-08-10 08:04:38');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('61', '61', 'eveniet', 'Deserunt eum atque soluta nulla aspernatur. Qui voluptatem veniam voluptatem recusandae possimus aut soluta. Dolor non voluptas rerum modi placeat dicta ullam.', '61', '1988-07-03 18:55:15');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('62', '62', 'et', 'Aut est libero inventore ad. Odio architecto ea vel sunt omnis asperiores nesciunt. Alias magnam et quo mollitia in. Delectus in perferendis rerum.', '62', '1975-08-12 12:26:58');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('63', '63', 'nihil', 'Cupiditate dolorum excepturi excepturi sint. Atque quos ab adipisci labore inventore in ipsam. Repellat laborum vitae corporis quisquam doloremque.', '63', '2003-09-24 01:31:06');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('64', '64', 'rem', 'Quis non iusto nihil autem enim. Mollitia et qui ipsa nihil est qui. Ad eos adipisci deleniti sint laborum.', '64', '1993-03-04 06:50:14');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('65', '65', 'natus', 'Molestiae sequi modi molestias quasi ad neque sit illum. Incidunt quis et adipisci reprehenderit omnis et. Autem et et ullam qui. Et quisquam commodi omnis consequatur culpa inventore iste nobis.', '65', '1985-11-15 16:24:49');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('66', '66', 'ea', 'Consequuntur recusandae hic a ab dolorem deserunt. Voluptas illum quia et. Et soluta tempore sunt quis eos dolor voluptas. Soluta ratione minus exercitationem maxime incidunt.', '66', '2000-11-22 04:36:33');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('67', '67', 'ea', 'Error nulla totam laboriosam sed neque cumque reprehenderit. Excepturi rerum delectus ut quo et sint expedita tenetur. Ut dolores deserunt odit tempora.', '67', '1993-10-01 09:48:37');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('68', '68', 'laudantium', 'Labore dolor beatae aut. Non saepe dolores recusandae et ut ipsam. Ea aut commodi quas molestiae perferendis.', '68', '2017-03-06 22:29:47');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('69', '69', 'neque', 'Earum omnis suscipit et reprehenderit quibusdam dolor. Exercitationem dolorem voluptatem ad ab deleniti. Voluptatem et veniam veniam qui ea unde quia. Ipsa ipsam praesentium non in id non doloribus ut. Reiciendis perspiciatis quod aliquam omnis mollitia.', '69', '2018-04-28 22:09:14');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('70', '70', 'id', 'At vero in impedit. Numquam vel deleniti cupiditate. Praesentium consequatur qui in et. Quam aperiam magnam dicta iusto sint quidem et in.', '70', '2007-02-06 21:14:14');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('71', '71', 'molestias', 'Quia quod voluptate blanditiis necessitatibus fuga incidunt. Asperiores sed architecto molestias autem tempora. Sed modi aliquam eum ex dolorum eligendi inventore minima. Saepe vel aut voluptate sit sunt sequi.', '71', '2006-02-07 21:03:43');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('72', '72', 'sequi', 'Quod animi est qui eos voluptatum ut quia. Autem maiores iure et quis voluptas. Sint ex aut qui est est est laborum.', '72', '2006-02-02 00:32:16');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('73', '73', 'sequi', 'Aut deleniti veniam est. Consequuntur adipisci in nesciunt. Quia reprehenderit perferendis repellendus qui ducimus. Eos beatae dolorum sint excepturi aliquid nobis. Nihil qui id eaque.', '73', '1992-12-05 09:55:45');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('74', '74', 'ullam', 'Eius incidunt natus doloremque ut consequuntur atque sed. Et velit eligendi qui nisi odio aliquam id totam. Enim adipisci cumque quasi sunt nostrum. Non facere ex eius ullam aut et natus.', '74', '1974-02-25 03:11:00');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('75', '75', 'ut', 'Voluptatibus nulla nihil hic quasi. Voluptatem enim consequatur quidem voluptates in accusamus. Nostrum illo et veritatis officia vel minima. Quis aut sit sunt consequatur et.', '75', '2004-02-06 06:54:55');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('76', '76', 'sint', 'Velit culpa esse atque sed. Nobis quaerat ab aut sed eveniet molestiae repellendus. Fugiat perferendis deleniti aut. Sunt dicta nulla quo deserunt architecto et ut doloribus.', '76', '2000-06-15 21:29:51');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('77', '77', 'esse', 'Veniam ex excepturi optio odit ex eius aut. Ea aut consequatur fugiat sint. Nisi qui ut explicabo facilis consectetur.', '77', '2017-03-23 14:32:25');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('78', '78', 'veritatis', 'Beatae repellendus ipsum quas aliquam et qui magnam. Accusamus dicta laudantium saepe facere doloremque ut earum quidem. Eveniet incidunt doloribus et ut.', '78', '2013-06-19 15:38:23');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('79', '79', 'qui', 'Exercitationem enim iste aspernatur fugiat. Amet tenetur non sint accusamus magni labore voluptatum. Ea quia consequatur in est nihil ea. Perferendis consequatur consectetur est et deserunt dicta.', '79', '1999-04-04 21:42:54');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('80', '80', 'aut', 'Nam odio perferendis saepe quia facere alias. Dolorem cupiditate inventore facilis. Repellat officia quo soluta ea consequatur eum. Consequatur id at quod facilis sit.', '80', '1992-09-29 21:45:26');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('81', '81', 'dolores', 'Aut laudantium consequatur autem. Voluptates distinctio rerum necessitatibus ut. Omnis expedita qui amet laudantium. Nisi perspiciatis quis unde repudiandae similique corrupti.', '81', '1993-04-04 14:54:18');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('82', '82', 'praesentium', 'Aut velit quasi deleniti rerum. Et ex error omnis facilis.', '82', '1972-03-06 23:11:44');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('83', '83', 'dolorem', 'Debitis assumenda quis qui consequuntur. Culpa id suscipit necessitatibus ut. Qui voluptatum delectus aspernatur accusantium sit velit dolorem minima.', '83', '2003-01-10 14:00:29');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('84', '84', 'consequatur', 'Aut sequi velit aut eligendi odit. Alias aut cumque unde incidunt. Saepe velit nihil iste odit eveniet. Suscipit alias sint doloribus.', '84', '1999-05-28 00:26:54');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('85', '85', 'explicabo', 'Ut molestiae vel in numquam. Voluptates qui enim sit perspiciatis possimus non. Consequatur aut voluptas accusamus veniam hic.', '85', '2001-08-08 06:29:09');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('86', '86', 'voluptatum', 'Incidunt cupiditate iure officia. Omnis debitis quia odit odit molestiae. Eligendi tempore esse delectus ut.', '86', '2016-10-24 14:22:39');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('87', '87', 'quia', 'Animi consequuntur commodi doloribus sed. Tempora enim molestiae aut veritatis. Et laboriosam nemo impedit distinctio earum.', '87', '2006-03-27 07:03:47');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('88', '88', 'voluptas', 'Impedit officiis ut omnis unde. Rerum sit vel quasi autem deleniti adipisci. Reiciendis expedita labore quam eaque incidunt dolorem illo. Nam harum id non voluptatem itaque facilis.', '88', '2000-02-06 00:09:43');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('89', '89', 'quia', 'Iste labore nobis blanditiis enim explicabo amet. Dicta ea eaque itaque magnam voluptatibus eveniet. Placeat corporis deleniti aperiam molestias placeat quia.', '89', '1976-10-01 23:55:39');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('90', '90', 'sequi', 'Deleniti est autem amet facilis enim. Omnis nobis impedit porro debitis commodi. Ad id vel dolor eum. Repudiandae asperiores molestiae quidem quo eos.', '90', '2007-05-20 14:26:56');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('91', '91', 'facilis', 'Et perspiciatis voluptatem aut. Iste corporis nemo voluptate perspiciatis tempora est. Ut hic et neque et exercitationem et. Aut deserunt voluptas voluptas quia.', '91', '1993-02-14 11:19:41');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('92', '92', 'voluptatem', 'Sed esse unde consequatur dolorem libero. Aut tenetur consequuntur accusamus autem molestiae architecto est.', '92', '1985-11-26 02:40:49');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('93', '93', 'ex', 'Animi ipsum nihil laborum suscipit reprehenderit perspiciatis. Veritatis sit rerum deleniti eligendi qui eos. Doloremque dolores dolor et est temporibus in. Architecto fuga unde ipsum ipsa et praesentium quibusdam ipsa. Repellendus et consequatur dolorem odit minus quas esse eum.', '93', '1997-06-24 20:20:20');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('94', '94', 'fuga', 'Recusandae qui non blanditiis aut. Rerum aut doloribus quo aut fugiat. Dolore omnis similique libero voluptatem quia quae vero. Molestiae veniam voluptatem voluptates maxime.', '94', '1980-03-12 02:16:01');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('95', '95', 'sed', 'Asperiores recusandae voluptatem qui recusandae non sequi sed vel. Aperiam voluptatem molestias cumque ipsa necessitatibus quia. Voluptatem vel occaecati necessitatibus ducimus nisi.', '95', '1995-01-23 01:57:26');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('96', '96', 'qui', 'Quis deserunt velit non et. Doloremque unde sint et sint aliquid quaerat quisquam. Dolore ullam dicta modi.', '96', '2005-02-16 02:46:02');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('97', '97', 'dolorem', 'Aliquam id tempore voluptatum assumenda. In sunt officiis nihil modi. Nulla ipsam iusto aut optio. Nihil voluptatem cum voluptatibus.', '97', '1971-07-15 00:36:24');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('98', '98', 'tenetur', 'Eos at qui impedit quam. Est sint ut animi doloribus ea. Similique ipsam voluptatem necessitatibus similique maxime eos. Officiis dolores natus necessitatibus quo blanditiis non maiores.', '98', '2013-09-01 20:20:05');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('99', '99', 'sed', 'Saepe sapiente aut ut vero dolor sunt eos rerum. Natus quia quo corrupti omnis aut eius. Iure expedita nobis consequuntur occaecati repudiandae et necessitatibus. Ad illo expedita aperiam non repellendus sint.', '99', '1981-06-08 18:23:56');
INSERT INTO `store` (`id`, `user_id`, `prod_name`, `description`, `photo_albums_id`, `create_date`) VALUES ('100', '100', 'repellendus', 'Excepturi tempora assumenda eos aperiam incidunt recusandae est amet. Et iusto voluptatum esse eveniet molestias explicabo.', '100', '1975-05-21 02:09:56');


